[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pyrogram>=2.0.106",
    "yt-dlp>=2025.3.31",
]
